#!/usr/bin/env python3

# Script Name: TCP Port Scanner using ICMP Ping
# Author: Festus Oguhebe Jr. 
# Purpose: TCP Port Scanner using ICMP to obtain IP Address

import sys
from scapy.all import sr1, IP, TCP, ICMP, sr, send
import random
from ipaddress import ip_network

def scan_port(host, dst_port):
    src_port = random.randint(1024, 65535)
    response = sr1(IP(dst=host)/TCP(sport=src_port, dport=dst_port, flags="S"), timeout=1, verbose=0)
    if response is None:
        print(f"Port {dst_port} is filtered and silently dropped")
    elif response.haslayer(TCP):
        if response.getlayer(TCP).flags == 0x12:
            send(IP(dst=host)/TCP(sport=src_port, dport=dst_port, flags="R"), verbose=0)
            print(f"Port {dst_port} is open")
        elif response.getlayer(TCP).flags == 0x14:
            print(f"Port {dst_port} is closed")

def icmp_ping_sweep(network):
    online_hosts = 0
    for ip in ip_network(network, strict=False).hosts():
        resp = sr1(IP(dst=str(ip))/ICMP(), timeout=1, verbose=0)
        if resp is None:
            print(f"Host {ip} is down or unresponsive.")
        elif resp.haslayer(ICMP):
            if int(resp.getlayer(ICMP).type) == 3 and int(resp.getlayer(ICMP).code) in [1, 2, 3, 9, 10, 13]:
                print(f"Host {ip} is actively blocking ICMP traffic.")
            else:
                print(f"Host {ip} is responding.")
                online_hosts += 1
    print(f"\n{online_hosts} hosts are online.")

def main_menu():
    while True:
        print("\nNetwork Security Tool")
        print("1. TCP Port Range Scanner")
        print("2. ICMP Ping Sweep")
        print("3. Exit")
        choice = input("Enter your choice: ")
        if choice == "1":
            host = input("Enter target host: ")
            port_range = [20, 21, 22, 23, 53, 69, 80, 123, 179, 264, 443, 520]
            for port in port_range:
                scan_port(host, port)
        elif choice == "2":
            network = input("Enter network address (CIDR format, e.g., 192.168.1.0/24): ")
            icmp_ping_sweep(network)
        elif choice == "3":
            break

if __name__ == "__main__":
    main_menu()